2024-10-24 14:42:02,482 file.manager INFO 2.0.2
2024-10-24 14:42:02,482 file.manager INFO Copyright (C) 2003-2024, Noriaki Ando and OpenRTM development team,
2024-10-24 14:42:02,482 file.manager INFO   Intelligent Systems Research Institute, AIST,
2024-10-24 14:42:02,482 file.manager INFO Copyright (C) 2024, Noriaki Ando and OpenRTM development team,
2024-10-24 14:42:02,482 file.manager INFO   Industrial Cyber-Physical Research Center, AIST,
2024-10-24 14:42:02,482 file.manager INFO   All right reserved.
2024-10-24 14:42:02,482 file.manager INFO Manager starting.
2024-10-24 14:42:02,482 file.manager INFO Starting local logging.
2024-10-24 14:42:02,486 file.manager.namingmanager INFO NameServer connection succeeded: corba/localhost
2024-10-24 14:42:06,593 file.ManagerServant INFO Master manager not found
2024-10-24 14:42:06,593 file.LocalServiceAdmin INFO All the local services are enabled.
2024-10-24 14:42:06,598 file.manager INFO Component type conf file: SevSeg.conf loaded.
2024-10-24 14:42:06,599 file.ec_base INFO setRate(1000000.000000) done
2024-10-24 14:42:06,599 file.ec_base INFO setRate(1000.000000) done
2024-10-24 14:42:06,599 file.rtobject INFO 1 execution context was created.
2024-10-24 14:42:06,602 file.rtobject ERROR Traceback (most recent call last):
  File "C:\Users\shuns\AppData\Local\Programs\Python\Python312\Lib\site-packages\OpenRTM_aist\RTObject.py", line 1168, in on_initialize
    ret = self.onInitialize()
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shuns\workspace\SevSeg\SevSeg.py", line 96, in onInitialize
    self.addInPort("Signal",self._SignalIn)
                            ^^^^^^^^^^^^^^
AttributeError: 'SevSeg' object has no attribute '_SignalIn'. Did you mean: '_signalIn'?

2024-10-24 14:42:06,602 file.rtobject INFO Initial active configuration set is default.
2024-10-24 14:42:06,602 file.rtobject ERROR on_initialize() failed.
2024-10-24 14:42:06,602 file.ec_worker WARNING ExecutionContext is already stopped.
2024-10-24 14:42:06,602 file.ec_base ERROR Invoking on_shutdown() for each RTC failed.
2024-10-24 14:42:07,609 file.manager.namingoncorba ERROR Traceback (most recent call last):
  File "C:\Users\shuns\AppData\Local\Programs\Python\Python312\Lib\site-packages\OpenRTM_aist\NamingManager.py", line 231, in unbindObject
    self._cosnaming.unbind(name)
  File "C:\Users\shuns\AppData\Local\Programs\Python\Python312\Lib\site-packages\OpenRTM_aist\CorbaNaming.py", line 604, in unbind
    self._rootContext.unbind(name_)
  File "C:\Users\shuns\AppData\Local\Programs\Python\Python312\Lib\site-packages\CosNaming_idl.py", line 242, in unbind
    return self._obj.invoke("unbind", _0_CosNaming.NamingContext._d_unbind, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
CosNaming.NamingContext.NotFound: CosNaming.NamingContext.NotFound(why=missing_node, rest_of_name=[CosNaming.NameComponent(id='note', kind='host_cxt'), CosNaming.NameComponent(id='SevSeg0', kind='rtc')])

